chore(githook): exit when fails

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -2,8 +2,16 @@
 
 echo "Formatting Go files..."
 goimports -w .
+if [ $? -ne 0 ]; then
+  echo "goimports failed. Commit aborted."
+  exit 1
+fi
 
 echo "Running golangci-lint with fix..."
 golangci-lint run --fix
+if [ $? -ne 0 ]; then
+  echo "golangci-lint failed. Commit aborted."
+  exit 1
+fi
 
 echo "Done"
